### ISSUE TITLE
Quarterly histogram broken

### ISSUE THREAD

**Issue by misaochan** [whym/commons-app-stats#10]
Hi @whym ,

It seems like the quarterly histogram is broken again?

Sorry for the trouble, haha. :)

**Comment by whym** [comment]
Yes, same error from https://github.com/whym/commons-app-stats/issues/9.
> Exception: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: '\nSELECT /* SLOW_OK */ *\nFROM revision JOIN page ON rev_page = page_id JOIN comment ON rev_comment_id = comment_id\nWHERE (comment_text LIKE "%%using Android Commons%%" OR comment_text LIKE "%%Via Commons Mobile App%%" OR comment_text LIKE "%%COM:MOA\\|Commons%%")\nAND rev_timestamp > "20130101" AND rev_timestamp < "21000101"\nORDER BY rev_timestamp DESC\n'] (Background on this error at: http://sqlalche.me/e/e3q8)

I'm looking into it, but it will take some time, partly because one run takes several hours in the current implementation.

**Comment by whym** [comment]
As a temporary measure, I'm trying a shorter time period of 2015-, which seems to work. Let's see if it works stably. (and in the meantime see https://github.com/whym/commons-app-stats/issues/9#issuecomment-437860835 for older data points.)
![image](https://user-images.githubusercontent.com/10674/48979340-e0476400-f0fc-11e8-9291-8f79a614ba01.png)

**Comment by misaochan** [comment]
The shorter period works for me too (just checked). Thanks so much @whym :)
