### ISSUE TITLE
Quarterly stats displaying only thin lines

### ISSUE THREAD

**Issue by misaochan** [whym/commons-app-stats#12]
Hi @whym , I think the quarterly stats might be broken - they only display lots of thin lines to me (instead of the histogram).

**Comment by whym** [comment]
I'm working on it, but it looks like the script is quite unstable right now. I didn't change the code, so it must be the amount of the recent data or some changes in the database side that is causing that.

A remedy I'm now trying is to discarding expensive text patterns to catch really old versions of the app. It might cause some data missing (like users who haven't updated the app for 4 years and still using it), but I expect the difference would be minimal.

**Comment by misaochan** [comment]
Thanks for your effort. :) Yes, I think it's fine to omit users running version 1 of the app for our purposes.

**Comment by misaochan** [comment]
Hmm, the current version isn't broken anymore, but the numbers don't look right. Is this WIP, maybe I should check back later? :)

**Comment by whym** [comment]
superseded - #13
