### ISSUE TITLE
No more data after 2023Q1

### ISSUE THREAD

**Issue by nicolas-raoul** [whym/commons-app-stats#17]
Both the chart and CSV seem to stop on March 20, 2023:

https://commons-app-stats.toolforge.org/latest_quarter.csv.gz

Maybe the tool stopped running?

**Comment by whym** [comment]
Trying to restart it - the script is slow and it might take a few hours.

It looks like the reason is that I forgot to schedule the quarterly one after [the migration](https://phabricator.wikimedia.org/T319639#8727661) this year. (The weekly one has been updated so I didn't notice.)

**Comment by whym** [comment]
It should be restored now.
