### ISSUE TITLE
Weekly stats stalled?

### ISSUE THREAD

**Issue by misaochan** [whym/commons-app-stats#2]
Hi @whym ,

I just glanced at this chart today and it seems that the weekly stats have stalled? The last bar was from 18 Feb 2018. Is it normal to have a month's lag time, or is something wrong with the stats?

Also, does this affect the quarterly count at 2018 Q1?

Thanks!

**Comment by whym** [comment]
Thanks for notifying, yes, it looks like there is something wrong:

> ImportError: Missing required dependencies ['numpy']

Working on it. (I think I need to update my virtualenv.)

**Comment by misaochan** [comment]
Thanks @whym ! That's a relief, since I was wondering why the quarterly stats are so low. :)
