### ISSUE TITLE
Swap colors around for deletes and edits?

### ISSUE THREAD

**Issue by misaochan** [whym/commons-app-stats#7]
Minor issue, but red is typically associated with "bad", aka deletions IMO. Strange to see edits in red and deletions in green. :)

**Comment by whym** [comment]
I agree. Actually #6 is the intended approach to fix it. (My bad, I wrote a solution but no symptom.)

**Comment by whym** [comment]
In the meantime, the rendered results are in SVG, so it should be possible to retouch them manually with an application like Inkscape. It is certainly a pain, though.
