### ISSUE TITLE
Stats stuck on week of 16 Sep

### ISSUE THREAD

**Issue by misaochan** [whym/commons-app-stats#8]
@whym Seems like the last week recorded at https://tools.wmflabs.org/commons-app-stats/ is 16 Sep?

**Comment by misaochan** [comment]
Hi @whym , any chance we can get this fixed? As a few people are asking for stats. :)

**Comment by whym** [comment]
Sorry, it looks like it slipped my mind. Fix in progress now. (With smaller samples it worked fine. Real queries take ~1 hour, so I don't know the actual results yet.)

**Comment by misaochan** [comment]
Thanks so much! @neslihanturan let me know if you need any further stats for your hackathon. :)

**Comment by whym** [comment]
Nearly done - the legend labels still look strange (such as "action, 1. upload (new)"). Hopefully the next run will fix that.

**Comment by whym** [comment]
Looks like it worked:
![latest](https://user-images.githubusercontent.com/10674/47598281-d71b8800-d9d4-11e8-9978-51e79ae1dc90.png)
![latest_quarter](https://user-images.githubusercontent.com/10674/47598280-d5ea5b00-d9d4-11e8-8d0d-907892a136cd.png)
